version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: npm start
    user: "node"

  firebase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firebase-emulator
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"  # UI
      - "8080:8080"  # Firestore
      - "9099:9099"  # Auth
    environment:
      - FIREBASE_TOKEN=${FIREBASE_TOKEN}
    command: firebase emulators:start --project demo-project
